# Generated by Django 3.2.8 on 2021-10-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('women', 'women'), ('men', 'men'), ('kids', 'kids'), ('accessories', 'accessories'), ('cosmetic', 'cosmetic')], default='women', max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
