# Generated by Django 3.2.8 on 2021-10-25 15:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211025_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XXS', 'XXS'), ('Xs', 'XS'), ('XS-S', 'XS-S'), ('M', 'M'), ('M-L', 'M-L'), ('L', 'L'), ('XL', 'XL')], max_length=22),
        ),
    ]
