# Generated by Django 3.2.8 on 2021-10-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.AddField(
            model_name='product',
            name='PriceAfterDiscount',
            field=models.IntegerField(default=0),
        ),
    ]
