# Generated by Django 3.2.8 on 2021-10-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211025_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
