# Generated by Django 3.2.8 on 2021-10-25 16:13

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('women', 'women'), ('men', 'men'), ('kids', 'kids'), ('accessories', 'accessories'), ('cosmetic', 'cosmetic')], default='women', max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('PriceAfterDiscount', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('XXS', 'XXS'), ('Xs', 'XS'), ('XS-S', 'XS-S'), ('M', 'M'), ('M-L', 'M-L'), ('L', 'L'), ('XL', 'XL')], max_length=22)),
                ('color', multiselectfield.db.fields.MultiSelectField(choices=[('White', 'White'), ('Black', 'Black'), ('Red', 'Red'), ('Grey', 'Grey'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow')], max_length=38)),
                ('image_one', models.ImageField(upload_to='images/%y/%m/%d/')),
                ('image_two', models.ImageField(upload_to='images/%y/%m/%d/')),
                ('image_three', models.ImageField(upload_to='images/%y/%m/%d/')),
                ('image_four', models.ImageField(upload_to='images/%y/%m/%d/')),
                ('image_five', models.ImageField(upload_to='images/%y/%m/%d/')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
