# Generated by Django 3.2.8 on 2021-10-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_five',
            field=models.ImageField(null=True, upload_to='images/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_four',
            field=models.ImageField(null=True, upload_to='images/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_three',
            field=models.ImageField(null=True, upload_to='images/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_two',
            field=models.ImageField(null=True, upload_to='images/%y/%m/%d/'),
        ),
    ]
