# Generated by Django 3.2.8 on 2021-10-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211025_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d/'),
        ),
    ]
