# Generated by Django 3.2.8 on 2021-10-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211025_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
