# Generated by Django 3.2.8 on 2021-10-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('coat', 'coat'), ('jacket', 'jacket'), ('dress', 'dress'), ('shirt', 'shirt'), ('T-shirt', 'T-shirt'), ('jeans', 'jeans')], default='coat', max_length=15),
        ),
    ]
