# Generated by Django 3.2.8 on 2021-10-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PriceAfterDiscount',
            field=models.IntegerField(default=0, verbose_name='if this product is sale'),
        ),
    ]
