# Generated by Django 3.2.8 on 2021-10-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_priceafterdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PriceAfterDiscount',
            field=models.IntegerField(default=0, verbose_name='If the product has discounts, what is the price after the discounts?'),
        ),
    ]
